apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
    environment: dev
  #namespace: roboshop
spec:
#labels are used as selectors to select the pods to which this service will route the traffic
  selector:
    project: roboshop
    tier: backend
    component: catalogue
    environment: dev
  ports:
    - protocol: TCP
      port: 27017  #service port
      targetPort: 27017  #container port